### ISSUE TITLE
Use @radix-ui/themes Skeleton component 

### ISSUE THREAD

**Issue by MiracleHorizon** [MiracleHorizon/scissors#82]
Wait for @radix-ui/themes 2.1.0 release and use the Skeleton component instead of the react-loading-skeleton library

https://github.com/radix-ui/themes/pull/188

**Comment by MiracleHorizon** [comment]
Don't forget to remove the following code from the globals.css

```css
/* react-loading-skeleton */
span[aria-live='polite'] {
  height: inherit;
  display: flex;
  align-items: center;
}

.dark .react-loading-skeleton {
  --base-color: #333333;
  --highlight-color: #444444;
}
```
